kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: kiali-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: kiali-http-80
      number: 80
      protocol: HTTP
    hosts:
    - "*"
      
# TO ENABLE TLS
#      tls:
#        mode: SIMPLE # enables HTTPS on this port
#        credentialName: kiali-cert-ingress