apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  hub: docker.io/querycapistio
  profile: demo
  components:
    pilot:
      k8s: # each components have to set this
        affinity: &affinity
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                        - arm64
                        - amd64
    egressGateways:
      - k8s:
          affinity: *affinity
          enabled: true
    ingressGateways:
      - k8s:
          affinity: *affinity
          service:
          ports:
            - name: status-port
              port: 15021
              nodePort: 30267
              targetPort: 15021
            - name: http2
              port: 80
              nodePort: 31480
              targetPort: 8080
            - name: https
              port: 443
              nodePort: 31443
              targetPort: 8443
            - name: tls
              port: 15443
              nodePort: 30057
              targetPort: 15443