kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: jaeger-gateway
  namespace: istio-system
spec:
  servers:
    - hosts:
        - jaeger.teste.com.br
      port:
        name: jaeger-https-443
        number: 443
        protocol: HTTPS
      # FROM TLS BE ENABLE
      tls:
        mode: SIMPLE # enables HTTPS on this port
        credentialName: jaeger-cert-ingress
  selector:
    istio: ingressgateway
