apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: arm64-affinity-patch
  namespace: istio-system
spec:
  hub: docker.io/querycapistio

  # ingressControllerMode: STRICT
  # enableAutoMtls: true

  meshConfig:
    # CONTROLE DA SAIDA PELO EGRESS
    outboundTrafficPolicy:
      # BLOCK
      mode: REGISTRY_ONLY
      # ALLOW
      #mode: ALLOW_ANY

    # ACCESS LOG OPTION
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON

  components:
    pilot:
      k8s:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
              weight: 2
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
    ingressGateways:
    - namespace: istio-system
      name: istio-ingressgateway
      enabled: true
      k8s:
        # Service Configuration
        service:
          type: NodePort # default is LoadBalancer
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
              weight: 2
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
    egressGateways:
    - namespace: istio-system
      name: istio-egressgateway
      enabled: true
      k8s:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
              weight: 2
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64