apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: arm64-affinity-patch
  namespace: istio-system
spec:
  profile: default
  hub: docker.io/querycapistio

  meshConfig:
    ingressControllerMode: STRICT
    enableAutoMtls: true
    # CONTROLE DA SAIDA PELO EGRESS
    outboundTrafficPolicy:
      # BLOCK
      mode: REGISTRY_ONLY
      # ALLOW
      #mode: ALLOW_ANY

    # ACCESS LOG OPTION
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON

  components:
    pilot:
      k8s:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
              weight: 2
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
    ingressGateways:
    - namespace: istio-system
      name: istio-ingressgateway
      enabled: true
      k8s:
        # Service Configuration
        service:
          type: NodePort # default is LoadBalancer

          # CUSTOM PORT 5000 - EXCLUSIVE FOR GRPC ( NECESSARY FOR NODE PORT )
          ports:
          - name: grpc
            protocol: TCP
            port: 5000
            targetPort: 5000
          
          # DEFAULT PORTS - NECESSARY WHEN CUSTOM PORTS ARE ADDED
          - name: https
            protocol: TCP
            port: 443
            targetPort: 8443

          - name: http
            protocol: TCP
            port: 80
            targetPort: 8080

          - name: healthcheck
            protocol: TCP
            port: 15021
            targetPort: 15021

        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
              weight: 2
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
    egressGateways:
    - namespace: istio-system
      name: istio-egressgateway
      enabled: true
      k8s:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
              weight: 2
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64