apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert-ingress
  namespace: istio-system
spec:
  secretName: grafana-cert-ingress
  dnsNames:
    - grafana.teste.com.br
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---